# backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thaiha-guestbook-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thaiha-backend
  template:
    metadata:
      labels:
        app: thaiha-backend
    spec:
      containers:
        - name: thaiha-backend
          image: ghcr.io/thaiha-hub/thaiha-guestbook-backend:fc53f3079b552a8b7f1e854e6ed5b593c4901667
          envFrom:
            - configMapRef:
                name: thaiha-guestbook-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: thaiha-postgres-secret
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: thaiha-redis-secret
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 8080
          resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"


