apiVersion: apps/v1
kind: Deployment
metadata:
  name: thaiha-guestbook-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thaiha-redis
  template:
    metadata:
      labels:
        app: thaiha-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: thaiha-redis-secret
                  key: REDIS_PASSWORD
          command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
