apiVersion: v1
kind: Service
metadata:
  name: thaiha-frontend
spec:
  selector:
    app: thaiha-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: thaiha-backend
spec:
  selector:
    app: thaiha-backend
  ports:
    - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: thaiha-postgres
spec:
  selector:
    app: thaiha-postgres
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: thaiha-redis
spec:
  selector:
    app: thaiha-redis
  ports:
    - port: 6379

